// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActions() {
  return window['go']['main']['App']['GetActions']();
}

export function HasSavedKey() {
  return window['go']['main']['App']['HasSavedKey']();
}

export function SaveAction(arg1) {
  return window['go']['main']['App']['SaveAction'](arg1);
}

export function SaveOpenAIKey(arg1) {
  return window['go']['main']['App']['SaveOpenAIKey'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}
