// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {openai} from '../models';

export function GetActions():Promise<{[key: number]: main.Action}>;

export function HasSavedKey():Promise<boolean>;

export function SaveAction(arg1:main.Action):Promise<void>;

export function SaveOpenAIKey(arg1:string):Promise<string>;

export function SendMessage(arg1:Array<openai.ChatCompletionMessage>,arg2:number):Promise<string>;
