// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasSavedKey():Promise<boolean>;

export function SaveOpenAIKey(arg1:string):Promise<string>;
