// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HasSavedKey() {
  return window['go']['main']['App']['HasSavedKey']();
}

export function SaveOpenAIKey(arg1) {
  return window['go']['main']['App']['SaveOpenAIKey'](arg1);
}
